********** 04/07/2016 00:51:19 **********
Exception Type: System.Exception
Exception: Exception of type 'System.Exception' was thrown.
User: x Method Name: 
Stack Trace: 
   at LogUtility.Tests.InvokerTest.InvokerException() in C:\Livio\dotNET\LogUtility\LogUtility.Tests\InvokerTest.cs:line 35

********** 04/07/2016 00:59:13 **********
Exception Type: System.Exception
Exception: Exception of type 'System.Exception' was thrown.
User: x Method Name: 
Stack Trace: 
   at LogUtility.Tests.InvokerTest.InvokerException() in C:\Livio\dotNET\LogUtility\LogUtility.Tests\InvokerTest.cs:line 35

********** 04/07/2016 00:59:13 **********
Exception Type: System.Exception
Exception: Exception of type 'System.Exception' was thrown.
User: x Method Name: 
Stack Trace: 
   at LogUtility.Tests.InvokerTest.InvokerInnerException() in C:\Livio\dotNET\LogUtility\LogUtility.Tests\InvokerTest.cs:line 54

********** 04/07/2016 01:00:00 **********
Exception Type: System.Exception
Exception: Exception of type 'System.Exception' was thrown.
User: x Method Name: 
Stack Trace: 
   at LogUtility.Tests.InvokerTest.InvokerException() in C:\Livio\dotNET\LogUtility\LogUtility.Tests\InvokerTest.cs:line 35

********** 04/07/2016 01:00:00 **********
Exception Type: System.Exception
Exception: Exception of type 'System.Exception' was thrown.
User: x Method Name: 
Stack Trace: 
   at LogUtility.Tests.InvokerTest.InvokerInnerException() in C:\Livio\dotNET\LogUtility\LogUtility.Tests\InvokerTest.cs:line 54

********** 04/07/2016 01:00:26 **********
Exception Type: System.Exception
Exception: Exception of type 'System.Exception' was thrown.
User: x Method Name: 
Stack Trace: 
   at LogUtility.Tests.InvokerTest.InvokerInnerException() in C:\Livio\dotNET\LogUtility\LogUtility.Tests\InvokerTest.cs:line 54

********** 04/07/2016 01:12:23 **********
Exception Type: System.Exception
Exception: Exception of type 'System.Exception' was thrown.
User: x Method Name: 
Stack Trace: 
   at LogUtility.Tests.InvokerTest.InvokerException() in C:\Livio\dotNET\LogUtility\LogUtility.Tests\InvokerTest.cs:line 35

********** 04/07/2016 01:12:23 **********
Exception Type: System.Exception
Exception: Exception of type 'System.Exception' was thrown.
User: x Method Name: 
Stack Trace: 
   at LogUtility.Tests.InvokerTest.InvokerInnerException() in C:\Livio\dotNET\LogUtility\LogUtility.Tests\InvokerTest.cs:line 54

